# Title
title: DarhangeR Rotations
description: Update/Download Page
# Theme variables
theme: jekyll-theme-slate
# Author Variable
show_downloads: true
github:
  show_github_button: false
  zip_url: https://www.mediafire.com/file/x28w46ed7wp9xii/ni_by_DarhangeR.zip/file